spring:
  datasource:
    name: signature
    url: jdbc:mysql://localhost:3306/signature
    username: root
    password: dongAI1221
    type: com.mysql.cj.jdbc.MysqlDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB

  mvc:
    async:
      request-timeout: 80000

  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: -1
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 300

mybatis:
  configuration:
    # 下划线转驼峰
    map-underscore-to-camel-case: true


server:
  port: 8082

# 要扫描的包记录日志信息
#logging:
#  config: classpath:log4j2.xml
#  level: fatal
