spring:
  datasource:
    name: signature
    url: jdbc:mysql://121.40.244.47:3306/app
    username: root
    password: mysql5.6
    type: com.mysql.cj.jdbc.MysqlDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-active: 20
      initial-size: 1
      min-idle: 1
      max-wait: 6000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      log-validation-errors: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis:
  configuration:
    # 下划线转驼峰
    map-underscore-to-camel-case: true

server:
  port: 8080

# 要扫描的包记录日志信息
#logging:
#  config: classpath:log4j2.xml
#  level: fatal